id: hl7.fhir.us.test-ig
canonical: http://hl7.org/fhir/us/test-ig
name: test_ig
title: "Test IG"
description: "An IG solely for testing."

status: draft
license: CC0-1.0 #https://www.hl7.org/fhir/valueset-spdx-license.html
version: 1.0.0
fhirVersion: 5.0.0
copyrightYear: 2021+
releaseLabel: STU1

extension:
  - url: http://hl7.org/fhir/StructureDefinition/structuredefinition-wg  
    valueCode: brr
publisher:
  name: HL7 International / Biomedical Research and Regulation 
  url:  'http://www.hl7.org/Special/committees/rcrim' 
  email: brr@lists.HL7.org
jurisdiction: urn:iso:std:iso:3166#US "United States of America"

menu:
  Table of Contents: toc.html
#    eCTD Profiles Stage 2:
#    Substance Characterisation (3.2.S.3): eCTD32S3.html   
#    Product Batch Formula (3.2.P.3.2): eCTD32P32.html 
#    Product Characterisation of Impurities (3.2.P.5.5): eCTD32P55.html

#  DRAFT eCTD Profiles:
#    Product Container Closure System (3.2.P.7.0): eCTD32P70.html 
#    Substance Container Closure System (3.2.S.6.0): eCTD32S60.html
#    Batch Analyses (3.2.S.4.4 & 3.2.P.5.4): eCTDSP4454.html 
#    Stability Summary (3.2.S.7.1 & 3.2.P.8.1): eCTDSP7181.html
#    Stability Data (3.2.S.7.3 & 3.2.P.8.3): eCTDSP7383.html

parameters:
 releaselabel: true
 excludettl: true
 excludemap: true
 apply-wg: true
 jira-code: test-ig
 # {joint-iso-itu-t(2) country(16) us(840) organization(1) hl7(113883)}
 auto-oid-root: 2.16.840.1.113883.4.642.40.36
 special-url: http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl
    - https://www.uniprot.org
    - urn:oid:1.3.6.1.4.1.5193
    - http://unitsofmeasure.org
    - urn:oid:1.3.6.1.4.1.519.1
    - urn:oid:2.16.840.1.113883.4.82
    - https://www.fda.gov/drugs/drug-approvals-and-databases/drug-establishments-current-registration-site
    - urn:ietf:rfc:3986
#   validation: [allow-any-extensions, no-broken-links]




